/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jabainitmo.database;

import java.sql.*;
import java.time.LocalDate;

import jabainitmo.database.hibernate.HibernateHouseContext;
import jabainitmo.database.hibernate.HibernateStreetContext;
import jabainitmo.database.jdbc.*;

public class App {
    public static void main(String[] args) throws SQLException {
        var houseCtx = new HibernateHouseContext();
        var streetCtx = new HibernateStreetContext();

        System.out.println("Print all streets:");
        streetCtx.getAll().forEach(s -> System.out.println(s));

        System.out.println("Print all houses:");
        houseCtx.getAll().forEach(h -> System.out.println(h));

        var street = streetCtx.getById(2);
        street.setName("Jaba av.");
        street.setPostIndex(255);
        streetCtx.update(street);

        street = new Street();
        street.setName("LMAO st.");
        street.setPostIndex(1337);
        streetCtx.save(street);
        var house = new House();
        house.setName("PAO KEK");
        house.setDate(LocalDate.now());
        house.setFloors(5);
        house.setType(HouseType.COMMERCIAL);
        house.setStreet(streetCtx.getById(1));
        houseCtx.save(house);

        System.out.println("Print all streets after update:");
        streetCtx.getAll().forEach(s -> System.out.println(s));

        System.out.println("Print all houses after update:");
        houseCtx.getAll().forEach(h -> System.out.println(h));

        System.out.println("Print all houses on street:");
        houseCtx.getAllByStreetId(1).forEach(h -> System.out.println(h));
    }
}
