/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jabainitmo.database;

import java.sql.*;
import java.time.LocalDate;

import jabainitmo.database.jdbc.*;

public class App {
    public static void main(String[] args) throws SQLException {
        var houseCtx = new JdbcHouseContext();
        var streetCtx = new JdbcStreetContext();

        System.out.println("Print all streets:");
        streetCtx.getAll().forEach(s -> System.out.println(s));

        System.out.println("Print all houses:");
        houseCtx.getAll().forEach(h -> System.out.println(h));

        var street = streetCtx.getById(3);
        street.setName("Jaba av.");
        street.setPostIndex(255);
        streetCtx.update(street);

        streetCtx.deleteById(2);

        streetCtx.save(new Street(0, "LOL st.", 1337));
        houseCtx.save(new House(0, "OOO KEK", LocalDate.now(), 5, HouseType.COMMERCIAL, streetCtx.getById(1)));

        System.out.println("Print all streets after update:");
        streetCtx.getAll().forEach(s -> System.out.println(s));

        System.out.println("Print all houses after update:");
        houseCtx.getAll().forEach(h -> System.out.println(h));
    }
}
